name: dart_countries_states
description: >
  Just an example, not for publishing.
version: 0.0.6
author: Jose Fiorillo <jffiorillo@gmail.com>
homepage: https://github.com/jffiorillo/dart-countries-states

environment:
  sdk: ">=2.12.0 <3.0.0"